### PR TITLE
Refresh view when debug stopped

### PR DESCRIPTION
**Pull request by thegecko**
#### What it does

With reference to https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/issues/11, this PR refreshes the memory view when the debugger stops (e.g. for each step)

#### How to test

Open a memory view and step the debugger. Watch values change

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by colin-grant-work** [comment]
Code looks good. Do we want this behavior to be configurable as a preference? For now binary, but soon maybe off, on, or configurable by view (and we bring back the lock)?

**Comment by thegecko** [comment]
> Code looks good. Do we want this behavior to be configurable as a preference? For now binary, but soon maybe off, on, or configurable by view (and we bring back the lock)?

I like this idea. Shall we merge this PR and then extend functionality in the interests of small continuous changes?

**Comment by colin-grant-work** [comment]
> I like this idea. Shall we merge this PR and then extend functionality in the interests of small continuous changes?

I think it's desirable to be able to control this in any case, so what would you think of doing the simple binary version (let's say `'off'` and `'on'` rather than boolean, to leave the door open) in this PR and considering a more advanced version later?

**Comment by thegecko** [comment]
> I think it's desirable to be able to control this in any case, so what would you think of doing the simple binary version (let's say 'off' and 'on' rather than boolean, to leave the door open) in this PR and considering a more advanced version later?

Implemented as described

**Review by colin-grant-work — APPROVED** [review]

**Pull request merged**
